routes/web.php
<?php

Route::get('/', 'TestController@welcome');

Auth::routes();

Route::get('/search', 'SearchController@show');
Route::get('/products/json', 'SearchController@data');

Route::get('/home','HomeController@index')->name('home');
Route::get('/products/{id}', 'ProductController@show'); // muestra la ficha de un producto
Route::get('/categories/{category}', 'CategoryController@show');

Route::post('/cart', 'CartDetailController@store'); // Alamacena los detalles del carrito asociado al cliente
Route::delete('/cart', 'CartDetailController@destroy'); // Elimina una línea del carrito activo de compra
Route::post('/order', 'CartController@update'); // Actualiza el carrito activo iniciado, con las lineas de pedido


// Aplicamos al grupo de rutas el middleware de admin, y si se pasa este se ejecuta el de admin
Route::middleware(['auth','admin'])->group(function () {
    Route::get('/admin/products', 'Admin\ProductController@index'); // listado de productos
    Route::get('/admin/products/create', 'Admin\ProductController@create');// Formulario para nuevos productos
    Route::post('/admin/products', 'Admin\ProductController@store'); // Almacena el nuevo producto en la BD
    Route::get('/admin/products/{id}/edit', 'Admin\ProductController@edit');// Formulario para nuevos productos
    Route::post('/admin/products/{id}/edit', 'Admin\ProductController@update'); // Aactualiza el nuevo producto en la BD
    Route::delete('/admin/products/{id}', 'Admin\ProductController@destroy');// Elimina el producto en la BD

    Route::get('/admin/products/{id}/images', 'Admin\ImageController@index'); // muestra las imágenes de un producto
    Route::post('/admin/products/{id}/images', 'Admin\ImageController@store');
    Route::delete('/admin/products/{id}/images', 'Admin\ImageController@destroy');
    Route::get('/admin/products/{id}/images/select/{image}', 'Admin\ImageController@select'); // Destacar imagen

    Route::get('/admin/categories', 'Admin\CategoryController@index'); // listado
    Route::get('/admin/categories/create', 'Admin\CategoryController@create');// Formulario para crear nuevos
    Route::post('/admin/categories', 'Admin\CategoryController@store'); // Almacena en la BD
    Route::get('/admin/categories/{category}/edit', 'Admin\CategoryController@edit');// Formulario para edicion
    Route::post('/admin/categories/{category}/edit', 'Admin\CategoryController@update'); // Actualizar
    Route::delete('/admin/categories/{category}', 'Admin\CategoryController@destroy');// Eliminar

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    // $product->category
    public function category(){
        return $this->belongsTo(Category::class);
    }

    // $product-images
    public function images(){
        return $this->hasMany(ProductImage::class);
    }

    // Accessor para imagen destacada
    public function getFeaturedImageUrlAttribute(){
        // obtenemos la imagen destacada del producto
        $featuredImage= $this->images()->where('featured', true)->first();
        // en caso que un producto no tenga imagen destacada, esta será la primera imagen asociada
        if (!$featuredImage)
            $featuredImage = $this->images()->first();
        // Si encontramos una imagen destacada, devolvemos su url
        if ($featuredImage){
            return $featuredImage->url;
        }
        // Devolvemos una imagen por defecto
        return '/images/products/default.gif';
    }

    public function getCategoryNameAttribute(){
        if($this->category)
            return $this->category->name;

        return 'General';
    }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    public function show(Request $request)
    {
        $query = $request->input('query');

        $products = Product::where('name', 'like', "%$query%")->paginate(5);
        // Redirigimos a la pagina del producto cuando se solo uno
        if ($products->count() === 1){
            $id = $products->first()->id;
            return redirect("/products/$id"); // == '/products/.$id
        }
        return view('search.show')->with(compact('products', 'query'));
    }

    // Función que devuelve un arreglo Json para el motor de sugerencias para buscar
    public function data()
    {
        //The pluck method retrieves all of the values for a given key:
        $products = Product::pluck('name');
        return $products;
    }
}

resources/views/search/show.blade.php
@extends('layouts.app')

@section('title', 'UAZON Resultados búsqueda')

@section('body-class', 'profile-page sidebar-collapse')

@section('content')

<div class="page-header header-filter" data-parallax="true" style="background-image: url('{{ asset('img/biblioteca.jpg') }}')"></div>

<div class="main main-raised">
    <div class="profile-content">
        <div class="container">
            <div class="row">
                <div class="col-md-6 ml-auto mr-auto">
                    <div class="profile">
                        <div class="avatar">
                            <img src="{{ asset('/img/search.jpg') }}"
                                 alt="Imagen de una lupa" class="img-circle img-fluid">
                        </div>
                        <div class="name">
                            <h3 class="title">Resultados de búsqueda</h3>
                        </div>
                        <div class="description text-center">
                            <p class="title">Se encontraron {{ $products->count() }} libros para el término {{ $query }}.</p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="team">
                <div class="row text-center">
                    @foreach($products as $product)
                        <div class="card col-md-4">
                            <div class="team-player">
                                <div class="card card-plain">
                                    <div class="col-md-6 ml-auto mr-auto">
                                        <img src="{{ $product->featured_image_url }}" alt="Imagen de producto" class="img-fluid">
                                    </div>
                                    <h4 class="card-title">
                                        <a href="{{ url('/products/'.$product->id) }}">{{ $product->name }}</a>
                                        <br>
                                        <small class="card-description text-muted">{{ $product->category_name }}</small>
                                        <p>{{ $product->description }}</p>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <div class="text-center">
                    {{ $products->links() }}
                </div>
            </div>

        </div>
    </div>
</div>


@include('includes.footer')
@endsection